### ISSUE TITLE
Relicense from Apache to GPLv3

### ISSUE THREAD

**Issue by dschuermann** [saschpe/BirthdayCalendar#1]
I haven't found a way to contact you in private so I am opening an issue for this:
This is a fork of https://github.com/SufficientlySecure/birthday-calendar so please adhere to the license and use GPLv3! If you want to discuss details email me at dominik@dominikschuermann.de

I don't really understand why you did this. Why not contribute to the original project?

**Comment by mvdan** [comment]
@dschuermann for the sake of evidence, could you point to any copy-pasted source code?

**Comment by dschuermann** [comment]
https://github.com/SufficientlySecure/birthday-calendar/blob/master/Birthday-Calendar/src/main/java/org/birthdayadapter/service/CalendarSyncAdapterService.java#L755

vs

https://github.com/saschpe/BirthdayCalendar/blob/master/mobile/src/main/java/saschpe/birthdays/service/CalendarSyncService.java#L139

**Comment by mvdan** [comment]
Okay, yeah, that's pretty solid.

It seems like OP hid the history, so it's hard to tell exactly what happened or why. Benefit of the doubt it is.

**Comment by saschpe** [comment]
Gah, before publishing to Github I used IntelliJ / Android Studio's "Update Copyright..." functionality. It seems like it replaced _all_ the licensing information in the respective files. Certainly not my intention but admittedly I didn't check afterwards.

Relicensing to GPLv3 is a non-issue for me and it's strong copyleft actually leaves no alternative either :-) I'll update copyright headers and add an acknowledgement section to the README.md to close this one, ok?

**Comment by saschpe** [comment]
Apache-2.0 is pretty common in the Android world, but that's certainly no excuse.

**Comment by saschpe** [comment]
@dschuermann Feel free to have a look

**Comment by dschuermann** [comment]
Yup that's okay.
Please also remove advertisements. You cannot include a closed source ad library into a GPLv3 licensed app.

**Comment by saschpe** [comment]
Fair enough, that will simplify the f-droid addition as well.

**Comment by krt16s** [comment]
You might want to update LICENSE.txt as well.
