### ISSUE TITLE
Add age to calendar entry.

### ISSUE THREAD

**Issue by zelleb** [saschpe/BirthdayCalendar#27]
Could you add the age someone turns to the entry? Something like "zelleb's birthday (33)"?

**Comment by saschpe** [comment]
That can be easily done but it often looks weird. It seems like people often store the day and month of a birthday. The year however is often wrong. On the other hand this might create an incentive to improve the data...

**Comment by PanderMusubi** [comment]
Please add this. Can also be an option users have to enable. For https://github.com/SufficientlySecure/birthday-calendar it is shown always, without any issues.

When people omit year of birth they might get motivated to add it. When they stored an incorrect year, also.

**Comment by PanderMusubi** [comment]
See also https://github.com/saschpe/BirthdayCalendar/issues/31
