### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [saschpe/BirthdayCalendar#6]
![image](https://user-images.githubusercontent.com/5357526/31932057-d0bd8ef2-b8ad-11e7-9338-1b4b4ed61d2c.png)

**Comment by JosephIbe** [comment]
I'm facing the same issue. How did you fix this?

**Comment by saschpe** [comment]
local.properties would have to contain details about the key store to use. The easiest way to get there is to invoke:

``./scripts/create-test-keystore``

**Comment by JosephIbe** [comment]
Thanks for the response. I have seen the script - `create-test-keystore` but how do I add it to local.properties file?

**Comment by saschpe** [comment]
Just run it. It will create a suitable local.properties (only if it doesn't already exit). I'm using this with CI automation...

**Comment by saschpe** [comment]
You can just axe it. I'll redo the Gradle bits at some point to use a different mechanism. For now, that would be the way :-)

**Comment by AndroidDeveloperLB** [comment]
I still have this issue:

![image](https://user-images.githubusercontent.com/5357526/75605440-85649f80-5aeb-11ea-97d8-c6bef1036cc7.png)

What do you mean "axe it" ? The issue still exists...

**Comment by saschpe** [comment]
You can safely remove `local.properties` and invoke the script. That will recreate a local.properties file with keys to be able to sign the release build. This way you can build the project.

**Comment by AndroidDeveloperLB** [comment]
@saschpe 
So why include the file if it's so problematic?
How come I can import other projects just fine? How can you use it if it has a problematic file?
And what script to run? You mean re-building, right?

If so, , your suggestion didn't work. See attached video:
[2020-02-29_12-09-06.zip](https://github.com/saschpe/BirthdayCalendar/files/4270155/2020-02-29_12-09-06.zip)

**Comment by saschpe** [comment]
```bash
rm local.properties
./scripts/create-test-keystore
./gradlew assemble
```

**Comment by AndroidDeveloperLB** [comment]
Guys why so much for importing of a project...
Please just fix it. It's not intuitive to perform this.
