### ISSUE TITLE
logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [saschpe/BirthdayCalendar#8]
Hi, I want to design a new logo for the project completely free...

**Comment by saschpe** [comment]
Sounds like a nice idea. Not sure what you have in mind but it would be great if was also done one XML to support the new animated icons

**Comment by Arslanshn** [comment]
https://steemit.com/utopian-io/@arslanshn/new-logo-proposal-for-birthdaycalendar-android-app

**Comment by saschpe** [comment]
Sorry for the delay. The icon looks great. I did a quick transform of the SVG and created Android assets based on it:
![screenshot_1524391458](https://user-images.githubusercontent.com/115275/39093794-6d242454-4625-11e8-85fc-90455dc3235d.png)
![screenshot_1524391471](https://user-images.githubusercontent.com/115275/39093795-6d416c6c-4625-11e8-9455-6fbf4ef1a0e4.png)

Going forward, I'd have to work on a couple more assets for the stores. Also, I'd like to add an attribution to the help section. Not sure what you'd want to see there

**Comment by saschpe** [comment]
I'm still playing around with the background color

**Comment by Arslanshn** [comment]
There's no problem with the delay.I will make a nice model in 2 days
